vim.o.cursorline = true
vim.o.cursorlineopt = "number"
vim.g.netrw_banner = 0
vim.g.netrw_keepdir = 0
vim.g.netrw_confirm = 0
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.guicursor = ""
vim.o.expandtab = false
vim.o.shiftwidth = 4
vim.o.smartindent = true
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.mouse = "a"
vim.o.number = true
vim.o.relativenumber = true
vim.o.numberwidth = 1
vim.o.ruler = true
vim.opt.shortmess:append("sI")
vim.o.signcolumn = "yes"
vim.o.timeoutlen = 400
vim.o.undofile = true
vim.opt.undodir = vim.fn.stdpath("cache") .. "/undo"
vim.opt.whichwrap:append("<>[]hl")
vim.g.loaded_node_provider = 0
vim.g.loaded_python3_provider = 0
vim.g.loaded_perl_provider = 0
vim.g.loaded_ruby_provider = 0
vim.o.laststatus = 2
vim.o.showmode = true
vim.opt.updatetime = 50
vim.opt.termguicolors = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.wrap = false
vim.opt.scrolloff = 10
vim.opt.lazyredraw = true
vim.opt.completeopt = { "menuone", "noselect" }
vim.opt.swapfile = false
vim.opt.backup = false
